### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by wesleyhf** [wesleyhf/pagarme-software-engineer-backend#1]
# Challenge ✨ 

- [ ] Done 😁

**References**
- https://github.com/pagarme/vagas/tree/master/desafios/software-engineer-backend

# Database 🐘

**Checklist:**
- [x] Structure - https://dbdiagram.io/d/5db8fcb6fa792a62f50da575
- [x] Generate

**References**
- https://www.dbml.org/docs/#table-definition

# Docker Environment 🐳

**Checklist:**

- [x] Node
- [x] PostgreSQL
- ~[ ] pgadmin4~
  - ~[ ] import servers~
- [x] Application
- [ ] Check Dev or Prod env

**References:**
- https://github.com/shipping-docker/vessel/blob/master/docker-files/vessel
- https://medium.com/@renato.groffe/postgresql-pgadmin-4-docker-compose-montando-rapidamente-um-ambiente-para-uso-55a2ab230b89
- https://www.pgadmin.org/docs/pgadmin4/3.6/export_import_servers.html
- https://itnext.io/lets-dockerize-a-nodejs-express-api-22700b4105e4

# Back-end ⚙️

**Checklist:**

- [x] Create structure
- [x] Database
  - [x] Migrations
  - [x] Models
  - [x] Factories
  - [x] Seeders
  - [x] Improve sequelize config files
- [x] Development
  - [x] transaction create
  - [x] transaction list
  - [x] balance
- [x] Middlewares
  - [x] Request validation (https://express-validator.github.io/docs/validation-result-api.html#formatwithformatter)
  - [x] Authenticate
- [x] .env

**References:**
- https://node-postgres.com
- https://sequelize.org (ORM)
- https://expressjs.com/pt-br/guide/using-middleware.html
- https://codewithhugo.com/sequelize-data-types-a-practical-guide/
- https://medium.com/riipen-engineering/testing-with-sequelize-cc51dafdfcf4
- https://www.freecodecamp.org/news/how-to-make-input-validation-simple-and-clean-in-your-express-js-app-ea9b5ff5a8a7/
- https://dev.to/santypk4/bulletproof-node-js-project-architecture-4epf
- https://blog.rocketseat.com.br/nodejs-express-sequelize/
- https://dev.to/nedsoft/a-clean-approach-to-using-express-validator-8go
- https://alligator.io/nodejs/creating-your-own-express-middleware/

# Documentation 📝

**Checklist:**

- [x] API
- [x] Dev
- [ ] Production

# Tests ✅ 

**Checklist:**

- [x] Config
- [x] Unit
- [x] Integrated
- [ ] E2E

**References:**
- https://jestjs.io/docs/en/configuration
- https://www.npmjs.com/package/eslint-plugin-jest
- https://medium.com/asos-techblog/javascript-quality-control-with-jest-and-eslint-b888eeb4b0c4

# Continuous Integration 🔁

- [ ] Setup (github actions (?))

# Continuous Delivery ⏩

- [ ] Setup

# Production 🎯 

- [ ] Find fast solution
- [ ] Setup
- [ ] Test it

**Comment by wesleyhf** [comment]
**THIS IS NOT THE FINAL VERSION**

First Database Structure: 

```dbml
enum payment_method {
    debit
    credit
}

enum payable_status {
  paid
  waiting_funds
}

Table transactions {
  id int [pk, increment]
  client_id int [ref: > clients.id]
  description text
  value float
  payment_method payment_method
  card_number int4
  card_name varchar
  card_expiry varchar
  created_at datetime [default: `now()`]
}

Table payables {
  id int [pk, increment]
  transaction_id int [ref: > transactions.id]
  client_id int [ref: > clients.id]
  status payable_status
  fee int2
  value float
  payment_date datetime
}

Table clients {
  id int [pk, increment]
  name varchar
}
```

![Pagar me Software Engineer Back-end Challenge](https://user-images.githubusercontent.com/2936121/67825668-d49cb400-faa8-11e9-9e87-402ff0624c96.png)

**Comment by wesleyhf** [comment]
I'm archiving this repository 'cause I learned a lot with the test and the interview.

Thank you @matheusvellone!
(I forgot the name/user of the other guy :sweat_smile:)

Late update from 2019-11-27 :grin:
